[build]
builder = "dockerfile"
dockerfilePath = "src/MarketLink.API/Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300
